include: package:all_lint_rules_community/all.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
    - "integration_test/test_bundle.dart"

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  errors:
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    collection_methods_unrelated_type: warning
    unrelated_type_equality_checks: warning
    deprecated_member_use_from_same_package: ignore
    parameter_assignments: warning
    todo: ignore

linter:
  rules:
    always_put_control_body_on_new_line: false
    always_specify_types: false
    diagnostic_describe_all_properties: false
    lines_longer_than_80_chars:
      exclude:
        - test/**
    public_member_api_docs: false
    prefer_double_quotes: false
    prefer_final_parameters: false
    prefer_relative_imports: false
    unnecessary_final: false
