name: japanana
description: "Flutter project to learn jp grammar."
publish_to: "none"

version: 1.0.2+7

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  hooks_riverpod: ^2.4.9
  intl: any
  kana_kit: ^2.0.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.2
  swipe_cards: ^2.0.0+1

dev_dependencies:
  all_lint_rules_community: ^0.0.3
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  patrol: ^3.4.0
  riverpod_lint: ^2.3.7

patrol:
  app_name: Japanana
  android:
    package_name: com.lucas_goldner.japanana
  ios:
    bundle_id: com.lucas-goldner.hikou
  macos:
    bundle_id: com.example.macos.hikou

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/data/Japanese Grammar Examples.md
    - test/assets/data/Japanese Grammar Examples TestData.md

  fonts:
    - family: Exlibris
      fonts:
        - asset: assets/font/Exlibris.otf
        - asset: assets/font/Exlibris-Bold.otf
          weight: 700
    - family: NotoSansJP
      fonts:
        - asset: assets/font/NotoSansJP.ttf
        - asset: assets/font/NotoSansJP-Bold.ttf
          weight: 700
