name: japanana
description: "Flutter project to learn jp grammar."
publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  hooks_riverpod: ^2.4.9
  intl: any
  percent_indicator: ^4.2.3
  swipe_cards: ^2.0.0+1

dev_dependencies:
  all_lint_rules_community: ^0.0.3
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  patrol: ^3.4.0
  riverpod_lint: ^2.3.7

patrol:
  app_name: Hikou
  android:
    package_name: com.example.hikou
  ios:
    bundle_id: com.lucas-goldner.hikou
  macos:
    bundle_id: com.example.macos.hikou

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/l10n/
    - assets/data/Japanese Grammar Examples.md
    - assets/images/
    - test/assets/data/Japanese Grammar Examples TestData.md
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
